environment:
  PYTHON: "C:\\Python34"
  PYTHON_VERSION: "3.4.1"
  PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell misc\\appveyor_install.ps1"

build: off

test_script:
  - "%PYTHON%\\Scripts\\tox.exe"
    #  - "%PYTHON%\\Scripts\\tox.exe -e unittests"
    #  - "%PYTHON%\\Scripts\\tox.exe -e smoke"
