environment:
  PYTHON: "C:\\Python34"
  PYTHON_VERSION: "3.4.1"
  PYTHON_ARCH: "64"

version: '{branch}-{build}'
cache: C:\Users\appveyor\pip\wheels
build: off

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell misc\\appveyor_install.ps1"

test_script:
  - "%PYTHON%\\Scripts\\tox.exe -e unittests_appveyor"
